export const POKEMON_DATA = [
  {
    pokemonId: 1,
    name: "bulbasaur",
    types: ["poison", "grass"],
    height: 0.7,
    weight: 6.9,
    genera: "seed pokemon",
    color: "green",
    isBaby: false,
    isLegendary: false,
    isMythical: false,
    abilities: [
      { name: "overgrow", hidden: false, desc: "", abilityId: 1 },
      { name: "chlorophyll", hidden: false, desc: "", abilityId: 2 },
    ],
    heldItems: [
      { name: "light ball", desc: "", cost: 1000, sprite: "", itemId: 1 },
      { name: "stardust", desc: "", cost: 100, sprite: "", itemId: 2 },
    ],
    areaEncounter: [
      "pallet",
      "route 3",
      "route 31",
      "route 23",
      "route 13",
      "route 7",
    ],
    training: {
      catchRate: 45,
      baseHappiness: 50,
      baseExperience: 64,
      hatchCounter: 20,
    },
    stats: {
      hp: 10,
      attack: 45,
      defense: 85,
      specialAttack: 12,
      specialDefense: 3,
      speed: 22,
    },
    moves: [
      {
        name: "tackle",
        desc: "",
        moveId: 1,
        accuracy: 40,
        pp: 35,
        power: 20,
        priority: 0,
        type: "normal",
      },
      {
        name: "tackle",
        desc: "",
        moveId: 1,
        accuracy: 40,
        pp: 35,
        power: 20,
        priority: 0,
        type: "normal",
      },
      {
        name: "tackle",
        desc: "",
        moveId: 1,
        accuracy: 40,
        pp: 35,
        power: 20,
        priority: 0,
        type: "normal",
      },
      {
        name: "tackle",
        desc: "",
        moveId: 1,
        accuracy: 40,
        pp: 35,
        power: 20,
        priority: 0,
        type: "normal",
      },
      {
        name: "tackle",
        desc: "",
        moveId: 1,
        accuracy: 40,
        pp: 35,
        power: 20,
        priority: 0,
        type: "normal",
      },
      {
        name: "tackle",
        desc: "",
        moveId: 1,
        accuracy: 40,
        pp: 35,
        power: 20,
        priority: 0,
        type: "normal",
      },
    ],
    sprites: {
      bulbasaur: {
        regular: "",
        shiny: "",
      },
      "bulbasaur-galar": {
        regular: "",
        shiny: "",
      },
    },
    evolutionChain: [],
  },
];
